(add-hook 'text-mode-hook
          #'(lambda ()
              ;;(refill-mode)
              ;;(flyspell-mode)
              (set-fill-column 134)
              (push '("\\geq" . ?≥) prettify-symbols-alist)
              (push '("\\leq" . ?≤) prettify-symbols-alist)
              (push '("\\neg" . ?¬) prettify-symbols-alist)
              (push '("\\rightarrow" . ?→) prettify-symbols-alist)
              (push '("\\leftarrow" . ?←) prettify-symbols-alist)
              (push '("\\infty" . ?∞) prettify-symbols-alist)
              (push '("-->" . ?→) prettify-symbols-alist)
              (push '("<--" . ?←) prettify-symbols-alist)
              (push '("\\exists" . ?∃) prettify-symbols-alist)
              (push '("\\nexists" . ?∄) prettify-symbols-alist)
              (push '("\\forall" . ?∀) prettify-symbols-alist)
              (push '("\\or" . ?∨) prettify-symbols-alist)
              (push '("\\and" . ?∧) prettify-symbols-alist)
              (push '(":)" . ?☺) prettify-symbols-alist)
              (push '("):" . ?☹) prettify-symbols-alist)
              (push '(":D" . ?☺) prettify-symbols-alist)
              (push '("^_^" . ?☻) prettify-symbols-alist)
              (push '(">=" . ?≥) prettify-symbols-alist)
              (push '("<=" . ?≤) prettify-symbols-alist)))

(provide 'init-text)
