* My coding style
:PROPERTIES:
:ID:       bf6b12ce-7fae-441d-a853-4982ab174139
:END:
#+BEGIN_SRC emacs-lisp
(defun my-setup-indent (n)
  ;; web development
  (setq coffee-tab-width n) ; coffeescript
  (setq javascript-indent-level n) ; javascript-mode
  (setq js-indent-level n) ; js-mode
  (setq js2-basic-offset n) ; js2-mode
  (setq web-mode-markup-indent-offset n) ; web-mode, html tag in html file
  (setq web-mode-css-indent-offset n) ; web-mode, css in html file
  (setq web-mode-code-indent-offset n) ; web-mode, js code in html file
  (setq css-indent-offset n) ; css-mode
  )

(defun my-coding-style ()
  (interactive)
  (message "My coding style!")
  (setq indent-tabs-mode t) ; use tab instead of space
  (my-setup-indent 4) ; indent 4 spaces width
  )
#+END_SRC
* web mode
:PROPERTIES:
:ID:       7734e329-acac-4a59-8418-7bb60bae1f46
:END:
(use-package php-eldoc :ensure t)

#+BEGIN_SRC emacs-lisp
(use-package web-mode :ensure t :config)
#+END_SRC


I'm not sure what the top one does.
#+BEGIN_SRC emacs-lisp
  (setq web-mode-extra-constants '(("php" . ("CONS1" "CONS2"))))
  ;; <?php expands to <?php ?>
  (setq web-mode-enable-auto-pairing t)
#+END_SRC


Open web-mode in html and phtml, and php files.
#+BEGIN_SRC emacs-lisp
  ;; Example - you may want to add hooks for your own modes.
  (add-to-list 'auto-mode-alist '("\\.html?\\'" . web-mode))
  (add-to-list 'auto-mode-alist '("\\.phtml?\\'" . web-mode))
  ;; I don't use php-mode and it is causing an error to load it in.
  ;;(use-package php-mode :ensure t)
  (add-to-list 'auto-mode-alist '("\\.php?\\'"  . web-mode))
  ;; when I open a css file use css-mode that way I can set up flychech with it!
  ;;(add-to-list 'auto-mode-alist '("\\.css?\\'" . web-mode))
  (add-to-list 'auto-mode-alist '("\\.js?\\'" . js2-mode))
  (add-to-list 'auto-mode-alist '("\\.css?\\'" . css-mode))
  (setq web-mode-extra-auto-pairs
        '(("erb"  . (("beg" "end")))
          ("php"  . (("beg" "end")
                     ("beg" "end")))
          ))

  (setq web-mode-engines-alist
        '(("php"  . "\\.php\\.")
          ("django"  . "\\.djhtml\\.")))
#+END_SRC


  ;;(setq web-mode-ac-sources-alist '(("css" . (ac-source-css-property ac-source-html-bootstrap+)) ("html" . (ac-source-words-in-buffer ac-source-abbrev ac-source-emmet-html-aliases ac-source-emmet-html-snippets ac-source-html-tag ac-source-html-attribute ac-source-html-attribute-2 ac-source-files-in-current-dir))))

   DO NOT SET ac-source yasnippet. autocomplete does NOT play nicely with ac-source yasnippet
   ac-source-yasnippet
   Here are some pages that talk about getting yas and autocomplete to play nicely together
   http://sethlakowske.com/why-i-use-emacs/fix-yasnippet-and-autocomplete-tab-key-collision/
   https://stackoverflow.com/questions/19900949/how-to-make-auto-complete-work-with-yasnippet-and-abbrev
   https://github.com/capitaomorte/yasnippet/issues/336
   https://emacs.stackexchange.com/questions/9670/yasnippet-not-working-with-auto-complete-mode
  I'm being more and more annoyed with ac-php
   https://github.com/xcwen/ac-php/
  ac-source-php
** web-mode hook
:PROPERTIES:
:ID:       4075a359-50e9-4144-ab63-3efc81ffd660
:END:
#+BEGIN_SRC emacs-lisp
(add-hook 'web-mode-hook '(lambda ()
                            ;;(use-package emmet-mode :ensure t)
                            ;; I've installed http://phpmd.org/ to check my php code using flycheck
                            ;; BUT flycheck mode does NOT support web-mode
                            (ggtags-mode 1)
                            ;; I have abbrev turned on for all prog-modes and all text modes.
                            ;; (abbrev-mode 1)
                            (diminish 'ggtags-mode)
                            ;;emmet mode for html % css related things
                            (emmet-mode)
                            ;; turn urls into clickable links.
                            (goto-address-mode)
                            (diminish 'emmet-mode)
                            (local-unset-key (kbd "C-<return>"))
                            (define-key web-mode-map (kbd "C-<return>") '(lambda ()
                                                                           (interactive)
                                                                           (newline)
                                                                           (evil-open-above 0)))
                            ;;(push '("function" . ?𝆑) prettify-symbols-alist)
                            ;; (push '(">=" . ?≥) prettify-symbols-alist)
                            ;; (push '("<=" . ?≤) prettify-symbols-alist)
                            ;; (push '("\\geq" . ?≥) prettify-symbols-alist)
                            ;; (push '("\\leq" . ?≤) prettify-symbols-alist)
                            ;; (push '("\\neg" . ?¬) prettify-symbols-alist)
                            ;; (push '("\\rightarrow" . ?→) prettify-symbols-alist)
                            ;; (push '("\\leftarrow" . ?←) prettify-symbols-alist)
                            ;; (push '("\\infty" . ?∞) prettify-symbols-alist)
                            ;; ;; this would make a comment look really weird <--  right-arrow
                            ;; ;;(push '("-->" . ?→) prettify-symbols-alist)
                            ;; (push '("<--" . ?←) prettify-symbols-alist)
                            ;; (push '("\\exists" . ?∃) prettify-symbols-alist)
                            ;; (push '("\\nexists" . ?∄) prettify-symbols-alist)
                            ;; (push '("\\forall" . ?∀) prettify-symbols-alist)
                            ;; (push '("\\or" . ?∨) prettify-symbols-alist)
                            ;; (push '("\\and" . ?∧) prettify-symbols-alist)
                            ;; (push '(":)" . ?☺) prettify-symbols-alist)
                            ;; ;;(push '("):" . ?☹) prettify-symbols-alist)
                            ;; (push '(":D" . ?☺) prettify-symbols-alist)
                            ;; (push '("^_^" . ?☻) prettify-symbols-alist)
                            ;; I should not enable aggressive indent mode for soihub files.
                            ;; There's no need to have lots of git diffs with files.
                            ;; unset web mode's C-c C-h command, because I want to use that for 'help
                            (local-unset-key (kbd "C-c C-h"))
                            (global-set-key (kbd "C-c C-h") 'help)))

#+END_SRC
* emmet-mode
:PROPERTIES:
:ID:       85cfa9dd-6596-4f96-aa47-53d695764199
:END:

#+BEGIN_SRC emacs-lisp

(use-package emmet-mode :ensure t)
(use-package ggtags  :ensure t)
#+END_SRC


;; use flycheck in php buffers as well. it's a real shame that flycheck doesn't support web-mode
;; (add-hook 'php-mode-hook (lambda ()
;;                            ;; I have abbrev mode turned on for all prog-modes and all text-modes
;;                            ;; (abbrev-mode 1)
;;                            (define-key php-mode-map (kbd "C-<return>") '(lambda ()
;;                                                                           (interactive)
;;                                                                           (newline)
;;                                                                           (evil-open-above 0)))
;;                            ;;(push '("function" . ?𝆑) prettify-symbols-alist)
;;                            (push '(">=" . ?≥) prettify-symbols-alist)
;;                            (push '("<=" . ?≤) prettify-symbols-alist)
;;                            (push '("->" . ?⟶) prettify-symbols-alist)
;;                            (push '("=>" . ?⟹) prettify-symbols-alist)
;;                            (push '("\\geq" . ?≥) prettify-symbols-alist)
;;                            (push '("\\leq" . ?≤) prettify-symbols-alist)
;;                            (push '("\\neg" . ?¬) prettify-symbols-alist)
;;                            (push '("\\rightarrow" . ?→) prettify-symbols-alist)
;;                            (push '("\\leftarrow" . ?←) prettify-symbols-alist)
;;                            (push '("\\infty" . ?∞) prettify-symbols-alist)
;;                            ;; this would make a comment look really weird <--  right-arrow
;;                            ;;(push '("-->" . ?→) prettify-symbols-alist)
;;                            (push '("<--" . ?←) prettify-symbols-alist)
;;                            (push '("\\exists" . ?∃) prettify-symbols-alist)
;;                            (push '("\\nexists" . ?∄) prettify-symbols-alist)
;;                            (push '("\\forall" . ?∀) prettify-symbols-alist)
;;                            (push '("\\or" . ?∨) prettify-symbols-alist)
;;                            (push '("\\and" . ?∧) prettify-symbols-alist)
;;                            (push '(":)" . ?☺) prettify-symbols-alist)
;;                            ;;(push '("):" . ?☹) prettify-symbols-alist)
;;                            (push '(":D" . ?☺) prettify-symbols-alist)
;;                            (push '("^_^" . ?☻) prettify-symbols-alist)
;;                            ;;(setq ac-sources '(ac-source-filename ac-source-words-in-buffer))
;;                            ))

* js
** tern-mode
:PROPERTIES:
:ID:       70766def-9c3f-40ae-b723-8c58407906a3
:END:
#+BEGIN_SRC emacs-lisp
(use-package tern :ensure t)

(add-hook 'js2-mode-hook (lambda () (tern-mode t)))
#+END_SRC
** minifying js
:PROPERTIES:
:ID:       f1e4ad29-7289-41e8-9596-3aa235a7679a
:END:
#+BEGIN_SRC emacs-lisp
(defun my-js-minify-function ()
  "Minifying my js files."
  (interactive)
  (async-shell-command (concat (format "closure --js  %s --js_output_file "
                                       (buffer-file-name))
                               (s-replace ".js" ".min.js" buffer-file-name)) "*js minifying*"))
(add-hook 'js2-mode-hook '(lambda ()
                            ;; I have abbrev turned on for all prog and text modes
                            ;; (abbrev-mode 1)
                            ;; (skewer-mode)
                            (ggtags-mode 1)
                            ;;(push '("function" . ?𝆑) prettify-symbols-alist)
                            (push '(">=" . ?≥) prettify-symbols-alist)
                            (push '("<=" . ?≤) prettify-symbols-alist)
                            (diminish 'ggtags-mode)
                            (add-hook 'after-save-hook 'my-js-minify-function nil t)))

(add-to-list 'display-buffer-alist (cons "\\\*js minifying\\\*" (cons #'display-buffer-no-window nil)))

#+END_SRC
* minifying css
:PROPERTIES:
:ID:       ebcdb679-72dc-4316-ba29-050129978b4c
:END:
#+BEGIN_SRC emacs-lisp
(defun my-css-minify-function ()
  "Minifying my css files."
  (interactive)
  (async-shell-command (concat (format "yuicompressor --type css  %s -o "
                                       (buffer-file-name))
                               (s-replace ".css" ".min.css" buffer-file-name)) "*css minifying*"))

(add-to-list 'display-buffer-alist (cons "\\\*css minifying\\\*" (cons #'display-buffer-no-window nil)))

(add-hook 'css-mode-hook '(lambda ()
                            (add-hook 'after-save-hook 'my-css-minify-function nil t)))
#+END_SRC
* provide this file
:PROPERTIES:
:ID:       11c040fb-db1c-476f-9212-dd6c4b082f34
:END:
#+BEGIN_SRC emacs-lisp
(provide 'init-html)
#+END_SRC
